---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment_from_github
  labels:
    app: nginx_from_github
spec:
  replicas: 8
  selector:
    matchLabels:
      app: nginx_from_github
  template:
    metadata:
      labels:
        app: nginx_from_github
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service_from_github
spec:
  selector:
    app: nginx_from_github
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress_from_github
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: main.ept
    http:
      paths:
      - path: /nginx_from_github
        pathType: Prefix
        backend:
          service:
            name: nginx-service_from_github
            port:
              number: 80

















#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: &app test-app
#spec:
# replicas: 21
#  selector:
#    matchLabels:
#      app: *app
#  template:
#    metadata:
#      labels:
#        app: *app
#    spec:
#      containers:
#      - name: *app
#        image: fabxc/instrumented_app
#        ports:
#        - name: web
#          containerPort: 8080
#        resources:
#          limits:
#            cpu: "0.1"
#            memory: 128Mi
#---
#kind: Service
#apiVersion: v1
#metadata:
#  name: &app test-app
#  labels:
#    service: *app
#spec:
#  selector:
#    app: *app
#  ports:
#  - name: web
#    port: 8080
##---
##kind: Service
##apiVersion: v1
##metadata:
##  name: &app test-app-np
#  labels:
#    service: *app
#spec:
#  type: NodePort
#  selector:
#    app: test-app
#  ports:
#  - name: web
#    port: 8080
#    nodePort: 32005
